### ISSUE TITLE
Add %[if darkMode]% conditional

### ISSUE THREAD

**Issue by yabdab** [yourhead/s4#46] opened 2018-12-30 12:57 UTC
Add %[if darkMode]% conditional so stack devs can include a "dark" themed version of edit mode when in Mojave Dark Mode.

**Comment by yourhead** [comment] 2018-12-30 21:24
i don't think it really makes sense to make this a conditional. it will just be a global CSS class in edit mode. but you'll be able to use it to style your edit mode UI when stacks is doing dark mode.

**Comment by yourhead** [comment] 2018-12-30 21:27
duplicate of #48

**Closed as completed by yourhead** 2018-12-30 21:27 UTC
Labels: enhancement, api
